# Introduction to Numpy

In [1]:
import numpy as np

In [2]:
x1 = np.array([3,5,6,8,43,6,13,56,])

In [3]:
x1

array([ 3,  5,  6,  8, 43,  6, 13, 56])

In [4]:
x1 = np.array([[3,5,6,8,43,6,13,56,],[3,5,6,8,43,6,13,56,],[3,5,6,8,43,6,13,56,]])

In [5]:
x1

array([[ 3,  5,  6,  8, 43,  6, 13, 56],
       [ 3,  5,  6,  8, 43,  6, 13, 56],
       [ 3,  5,  6,  8, 43,  6, 13, 56]])

In [6]:
x2 = np.arange(2,200,3)

In [7]:
x2

array([  2,   5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,
        41,  44,  47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,
        80,  83,  86,  89,  92,  95,  98, 101, 104, 107, 110, 113, 116,
       119, 122, 125, 128, 131, 134, 137, 140, 143, 146, 149, 152, 155,
       158, 161, 164, 167, 170, 173, 176, 179, 182, 185, 188, 191, 194,
       197])

In [14]:
x3 = np.linspace(2,25,retstep=True,num=10)

In [15]:
x3

(array([ 2.        ,  4.55555556,  7.11111111,  9.66666667, 12.22222222,
        14.77777778, 17.33333333, 19.88888889, 22.44444444, 25.        ]),
 2.5555555555555554)

In [18]:
# x4 = np.zeros(5)
x4 = np.zeros((4,4))

In [19]:
x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
x5 = np.ones((4,4))

In [21]:
x5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
x6 = np.identity(5,dtype=np.int32)

In [25]:
x6

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
list_1 = [[4,5,67,3,4,7,7],[5,3,4,7,8,3,4]]

In [27]:
x7 = np.asarray(list_1)

In [28]:
x7

array([[ 4,  5, 67,  3,  4,  7,  7],
       [ 5,  3,  4,  7,  8,  3,  4]])

In [29]:
np.random.random()

0.33625684694160385

In [31]:
np.random.random((4,4),)

array([[0.41048397, 0.55525144, 0.01863395, 0.65937148],
       [0.71506926, 0.94179629, 0.28580107, 0.83317521],
       [0.08524844, 0.33230053, 0.56032057, 0.63258205],
       [0.97296581, 0.80901461, 0.40014665, 0.53577675]])

In [33]:
np.random.randn(4,4)

array([[-0.35943508, -0.02578232,  0.03551729,  1.48822092],
       [ 0.58951724,  0.4301466 , -0.34578815, -0.06719556],
       [ 0.08444702,  1.44347437, -1.05752009,  0.31379931],
       [ 0.05568637,  0.14849472, -1.35012173,  2.25472748]])

In [38]:
np.random.randint(50,500,(4,4))

array([[324,  59, 119, 310],
       [349, 166, 257,  80],
       [ 62,  71, 146, 397],
       [494, 228, 461, 118]])

In [40]:
np.random.seed(4)
np.random.randint(100)

46

# Slicing Array

In [43]:
x = np.random.randint(5,50,(4,4))

In [44]:
x

array([[41, 49, 43, 47],
       [ 8,  5, 26, 26],
       [14, 43, 43,  7],
       [35, 13,  7, 28]])

In [45]:
x[2]

array([14, 43, 43,  7])

In [46]:
x[0:2]

array([[41, 49, 43, 47],
       [ 8,  5, 26, 26]])

In [47]:
x[0:2,0:2]

array([[41, 49],
       [ 8,  5]])

In [48]:
x[:,-1]

array([47, 26,  7, 28])

In [49]:
x[:,:-1]

array([[41, 49, 43],
       [ 8,  5, 26],
       [14, 43, 43],
       [35, 13,  7]])

# Numpy Methods

In [50]:
x = np.random.randint(1,100,25)

In [51]:
x

array([33, 41, 43, 46, 34, 33, 29,  4, 80, 99, 96, 58, 51, 18, 82, 90, 74,
       60, 49, 77, 24, 95, 23, 68, 63])

In [52]:
x.max()

99

In [53]:
x.min()

4

In [54]:
x.argmax()

9

In [55]:
x.argmin()

7

In [56]:
np.sort(x)

array([ 4, 18, 23, 24, 29, 33, 33, 34, 41, 43, 46, 49, 51, 58, 60, 63, 68,
       74, 77, 80, 82, 90, 95, 96, 99])

In [57]:
x.mean()

54.8

In [58]:
x.std()

26.396969523034272

In [59]:
np.median(x)

51.0

In [60]:
x.shape

(25,)

In [61]:
x.ndim

1

In [62]:
x.reshape(5,5)

array([[33, 41, 43, 46, 34],
       [33, 29,  4, 80, 99],
       [96, 58, 51, 18, 82],
       [90, 74, 60, 49, 77],
       [24, 95, 23, 68, 63]])

In [64]:
# np.vstack(x)
np.hstack(x)

array([33, 41, 43, 46, 34, 33, 29,  4, 80, 99, 96, 58, 51, 18, 82, 90, 74,
       60, 49, 77, 24, 95, 23, 68, 63])